config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :flags

  resources :tickets

  root 'tickets#index'

end

app/models/flag.rb
class Flag < ActiveRecord::Base
  has_and_belongs_to_many :tickets
  validates :title, uniqueness: true
  accepts_nested_attributes_for :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_and_belongs_to_many :flags
  belongs_to :user
  accepts_nested_attributes_for :flags
  def body_preview
    self.body[0..300] + if (self.body.length >= 300) then "..." else "" end
  end
  def small_title
    self.title[0..120] + if (self.body.length >= 300) then "..." else "" end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  before_action :set_flag, only: [:show, :edit, :update, :destroy]

  # GET /flags
  # GET /flags.json
  def index
    @flags = Flag.all
  end

  # GET /flags/1
  # GET /flags/1.json
  def show
  end

  # GET /flags/new
  def new
    @flag = Flag.new
  end

  # GET /flags/1/edit
  def edit
  end

  # POST /flags
  # POST /flags.json
  def create
    @flag = Flag.new(flag_params)

    respond_to do |format|
      if @flag.save
        format.html { redirect_to @flag, notice: 'Flag was successfully created.' }
        format.json { render :show, status: :created, location: @flag }
      else
        format.html { render :new }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flags/1
  # PATCH/PUT /flags/1.json
  def update
    respond_to do |format|
      if @flag.update(flag_params)
        format.html { redirect_to @flag, notice: 'Flag was successfully updated.' }
        format.json { render :show, status: :ok, location: @flag }
      else
        format.html { render :edit }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flags/1
  # DELETE /flags/1.json
  def destroy
    @flag.destroy
    respond_to do |format|
      format.html { redirect_to flags_url, notice: 'Flag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flag
      @flag = Flag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flag_params
      params.require(:flag).permit(:title)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    if params[:search]
      @tickets = Ticket.where(:id => params[:search])
    elsif params[:flags]  
      @tickets = Flag.where(:id => params[:flags]).first.tickets
    else
      @tickets = Ticket.all
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :body, :user_id, flag_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flags/_form.html.erb
<%= form_for(@flag) do |f| %>
  <% if @flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
      <% @flag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flags/edit.html.erb
<h1>Editing flag</h1>

<%= render 'form' %>

<%= link_to 'Show', @flag %> |
<%= link_to 'Back', flags_path %>

app/views/flags/index.html.erb
<h1>Listing flags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flags.each do |flag| %>
      <tr>
        <td><%= flag.title %></td>
        <td><%= link_to 'Show', flag %></td>
        <td><%= link_to 'Edit', edit_flag_path(flag) %></td>
        <td><%= link_to 'Destroy', flag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flag', new_flag_path %>

app/views/flags/new.html.erb
<h1>New flag</h1>

<%= render 'form' %>

<%= link_to 'Back', flags_path %>

app/views/flags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @flag.title %>
</p>

<%= link_to 'Edit', edit_flag_path(@flag) %> |
<%= link_to 'Back', flags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Snought" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <!-- Nav Bar -->
  <nav class="top-bar" data-topbar="">
    <!-- Title -->
    <ul class="title-area">
      <li class="name"><h1><a href="#"><h1><%= link_to 'S₀', root_url %></h1></li>
  
      <!-- Mobile Menu Toggle -->
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
  
    <!-- Top Bar Section -->
    
    <section class="top-bar-section">
  
      <!-- Top Bar Left Nav Elements -->
      <ul class="left">  
        <!-- Search | has-form wrapper -->
        <li class="has-form">
          <div class="row collapse">
	    <%= form_tag(tickets_path, :method => "get", id: "search-form") do %>
              <div class="large-8 small-9 columns">
  	        <%= text_field_tag :search, params[:search], placeholder: "Ticket #" %>
              </div>
              <div class="large-4 small-3 columns">
    	        <%= submit_tag "Search", :name => nil, class:"alert button expand" %>
              </div>
	    <% end %>
          </div>
        </li>
	<li>
	  <%= link_to 'Proxy', new_ticket_path %>
	</li>
	<li>
	  <%= link_to 'New Flag', new_flag_path %>
	</li>
      </ul>
      <ul class="right">  
        <li class="has-dropdown">
          <a href="#">Flags</a>
          <ul class="dropdown">
	    <% Flag.all.each do |f| %>
    	       <li><%= link_to f.title, root_url(:flags => f.id), :method => :get %></li>
	    <% end %>
          </ul>
        </li>
      </ul>
    </section>
  </nav>

  <body class="row">
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= simple_form_for @ticket do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title %><br>
  <%= f.input :body %><br>
  <%= f.association :flags, as: :check_boxes %> 
  <%= f.association :user, label: "Responsible" %> 
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h4>Listing tickets</h4>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Recv'd</th>
      <th>Updated</th>
      <th>Subject</th>
      <th>Body</th>
      <th>Responsible</th>
      <th>Flags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.id, ticket %></td>
        <td><%= ticket.created_at.to_date %></td>
        <td><%= ticket.updated_at.to_date %></td>
        <td><%= ticket.small_title %></td>
        <td><%= ticket.body_preview %></td>
        <td><%= if ticket.user then ticket.user.name end%></td>
        <td><% ticket.flags.each do |flag| %>
           <%= flag.title %>
        <% end %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @ticket.body %>
</p>


<strong>Flags:</strong>
<p><% @ticket.flags.each do |flag| %>
   <%= flag.title %>
<% end %></p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>